### ISSUE TITLE
How is this different from Laravel's Validator?

### ISSUE THREAD

**Issue by LorenzoSapora** [kukac7/external-url-validator#1]
Using validator, you can check external URLs.

```php
$request->validate([
    'url' => 'active_url'
]);
```

I've not actually installed your package, as you don't have a README, but I'd love to be corrected, if you're doing something interesting, like outputting the DNS query, or visually showing a dead URL.

**Comment by kukac7** [comment]
hi @LorenzoSapora 👋,

thank you for your feedback!
readme is in progress. 😉 

the [laravel validator](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L49) just does it to check if there is a record of 'a' or 'aaa' for the domain.

the component does that http request (guzzle) that the external url is works, valid.
plus you can specify your own api url to validate.

**Comment by LorenzoSapora** [comment]
Interesting, I look forward to your progress!
